%%{init: {'theme': 'neutral'}}%%

mindmap
  root((vs))
    id)データサイエンス(
      統計学
      ::icon(fa fa-square-root-alt)
      計量経済学
      ::icon(fa fa-money-bill-alt)
      データ可視化
      ::icon(fa fa-chart-bar)
        Matplotlib
        Tableau
        Power BI
      発表スキル
      ::icon(fa fa-file-powerpoint)
      最適化
      ::icon(fa fa-calculator)
      行動科学
      ::icon(fa fa-users)
        計画的行動理論
        合理的選択理論
        技術受容モデル
      ビジネス
      ::icon(fa fa-briefcase)
    id)機械学習(
      プロセッサ
      ::icon(fa fa-microchip)
        GPU
        TPU
        FPGA
      開発ツール
      ::icon(fa fa-keyboard)
        Git
        Docker
        クラウド
      機械学習
      ::icon(fa fa-robot)
        自然言語処理
        画像解析
