%%{init: {'theme': 'neutral'}}%%

mindmap
  root((vs))
    データサイエンティスト
      統計学
      計量経済学
      データ可視化
        Matplotlib
        Tableau
        Power BI
      発表スキル
      最適化
      行動科学
        計画的行動理論
        合理的選択理論
        技術受容モデル
      ビジネス
    機械学習エンジニア
      アクセラレータ
        GPUs
        TPUs
        FPGAs
      開発ツール
        Git
        Docker
        クラウド
      機械学習
        自然言語処理
        画像解析
