%%{init: {'theme': 'neutral'}}%%

timeline
    title 業務に必要なツール
    2012 : Matlab
    2013 : R
    2014 : SQL : JavaScript
    2015 : Bash : Python : MapReduce : Hive : Presto : cron
    2016 : PySpark : Scala
    2017 : WWW : AWS
    2018 : ArgGIS
    2019 : Docker : Git : Azure : BERT
    2022 : ChatGPT
