%%{init: {'theme': 'neutral'}}%%

flowchart
  root("視聴者のタイプ")
  c1("サービスに<br>興味がある")
  c2("サービスに<br>興味がない")
  c11("番組の放送時間")
  c12("モバイル<br>（デバイス、データ通信量など）")
  c1x("...")
  c21("番組のゲスト")
  c22("番組フォーマット")
  c2x("...")
  c1a(("最適化"))
  c1b(("ビジネス"))
  c2a(("ビジネス"))
  c2b(("予測"))
  
  root -->|1| c1
  root -->|2| c2
  c1 --> c11
  c1 --> c12
  c1 --> c1x
  
  c2 --> c21
  c2 --> c22
  c2 --> c2x
  
  c11 --> c1a
  c12 --> c1b
  c21 --> c2a
  c22 --> c2b
